[package]
name = "simon"
version = "0.1.0"
authors = ["Andrew Bowers <andrew.bowers@agamecoder.com>"]
edition = "2018"

[dependencies]
config = "0.9.2"
directories = "1.0"
failure = "0.1.5"
rand = "0.6.5"
serde = { version = "1.0.87", features = ["derive"] }
termion = "1.5.1"
tui = "0.3.0"
