[good-eats]
name = "Good Eats"
kind = "media"
priority = 9
media_dirs = [ "/mnt/Data/Videos" ]
media_types = [ "mp4", "mkv", "avi" ]
base_color = { "Rgb" = [10, 10, 10] }
    [good-eats.command]
    program = "mpv"
    args = [ "{0}" ]
    
        
